name: firebase_auth_dart
description: TODO
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_auth_platform_interface: ^6.1.0
  flutter:
    sdk: flutter
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  http: ^0.13.3
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  firebase_core:
    git:
      url: git://github.com/pr-Mais/flutterfire
      path: packages/firebase_core/firebase_core
      ref: "@mais/firebase-dart"

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
      # testing, later will be removed
      macos:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
