name: firebase_auth_dart
description: TBD
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_auth_platform_interface: ^6.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
dependency_overrides:
  firebase_core:
    git:
      url: git://github.com/pr-Mais/flutterfire
      path: packages/firebase_core/firebase_core
      ref: "@mais/firebase-dart"

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
      # testing, later will be removed
      macos:
        dartPluginClass: FirebaseAuthDart
        pluginClass: none
